### ISSUE TITLE
Add ability to set Event startTime and endTime

### ISSUE THREAD

**Issue by kxc171** [dynatrace-oss/dynatrace-github-action#537]
**Is your feature request related to a problem? Please describe.**
I would like to be able to specify the `startTime` and `endTime` for an event, as mentioned in the [Events v2](https://docs.dynatrace.com/docs/dynatrace-api/environment-api/events-v2/post-event) API.

**Describe the solution you'd like**
The YAML list for defining events should match the [Request body object](https://docs.dynatrace.com/docs/dynatrace-api/environment-api/events-v2/post-event#request-body-objects) and all it's options, as described in the API.

**Describe alternatives you've considered**
Alternatives would be querying the API directly instead of through the Action.

**Additional context**
This is hardcoded to not include these values as part of the payload, so there is no way to workaround this.
https://github.com/dynatrace-oss/dynatrace-github-action/blob/main/src/dynatrace.ts#L117-L123

**Comment by yul14nrc** [comment]
I saw that this issue is already merged on main branch, but when are you going to publish the new release @kxc171 ?

**Comment by kxc171** [comment]
@yul14nrc Unfortunately I can't publish any releases since I'm not actually part of the Dynatrace Team.

@wolfgangB33r - are there any plans to cut a new version? If you create a `v10.0.0` tag, the `release.yaml` workflow should also create the `v10` and `v10.0` tag for you. 😃

**Comment by yul14nrc** [comment]
@kxc171 thanks for the information. @wolfgangB33r as kyle mention, can you help us generating the new release for this?
Thanks a lot.

**Comment by kxc171** [comment]
@yul14nrc - it looks like `v9.1` has been cut so you can use that!
